### ISSUE TITLE
I just updated my TV and got this error

### ISSUE THREAD

**Issue by mattisaoldgit** [BrandonDusseau/braviaproapi#1]
```
Traceback (most recent call last):
  File "br.py", line 6, in <module>
    is_powered_on = television.system.get_power_status()
  File "/home/pi/.local/lib/python3.7/site-packages/braviaproapi/bravia/system.py", line 119, in get_power_status
    self.bravia_client.initialize()
  File "/home/pi/.local/lib/python3.7/site-packages/braviaproapi/braviaclient.py", line 64, in initialize
    raise ApiError("The target device is running an incompatible API version '{0}'".format(api_version))
braviaproapi.bravia.errors.apierror.ApiError: The target device is running an incompatible API version '5.2.0'
```
Can you help?

Thanks

**Comment by BrandonDusseau** [comment]
Hi Matt,
This library was designed and tested for devices running version 3.x.x of the Sony API, and yours appears to be running 5.2.0. Unfortunately my device is too old to upgrade to that version and as a result I cannot upgrade the library at this time.

You may have luck if you change the check in this file (see highlighted line) from `4.0.0` to `6.0.0`. Since this is a major software upgrade, I cannot guarantee that the library will be compatible. Perhaps some functions will work though.
https://github.com/BrandonDusseau/braviaproapi/blob/master/braviaproapi/braviaclient.py#L61

**Edit:** I should clarify that in this case you will need to use a local copy of the library instead of the version installed from pip. Can you please let me know the model and software version of your TV so that I can update the documentation?

Best of luck! If you'd like to contribute to this library, please see the README file for contribution instructions.

Thanks for using my package!

**Comment by BrandonDusseau** [comment]
Update: it looks like my model is compatible with Android 8! I will see about upgrading this library, but it may be a week or two as I have been feeling unwell.

**Comment by BrandonDusseau** [comment]
Update: I've updated my TV to Oreo and found that it is still running a 3.x version of the API. I will leave this issue open for the moment. Later I will investigate the current API documentation and determine if any changes need to be made to the library to enable compatibility.

In the meantime, I have updated the documentation to indicate that devices not running the 3.x API are not supported.

Thanks for pointing this issue out!

**Comment by mattisaoldgit** [comment]
Hi Brandon,

Many thanks for the response, I changed the suggested line and it worked! well some of it did, for example the list all Apps returned lots of errors, but volume worked. When I get more time over the next few days I will compare to Sony's updated API calls and test features to see what works and what must be altered. I will post back, I am very much a newbie when it comes to code, so I have no real idea about updating forks and branches but I will at the very least be able to save you some update time :)

I am also using your program through MQTT, so a MQTT listener calls your code which fires the command to the TV. let me know if you would be interested in having that code/setup, I thought it might be nice for others that are getting into MQTT?

Thanks for you hard work

Matt

**Comment by BrandonDusseau** [comment]
I was just browsing through the API documentation and Sony doesn't appear to have updated it. Can you please let me know your device model and software version? Also can you please provide more information about the errors you saw with the application list?

Thanks!

**Comment by BrandonDusseau** [comment]
@mattisaoldgit Are you still having issues? Please provide the requested information above so that I can try to determine next steps.
